#!/bin/bash
#
# install freeling
# LDFLAGS temporarily unset to avoid /u/metanet/tools64/lib, which has 
# libboost libs without "mt", 
# causing make to fail with undefined reference to boost::program_options:: etc.
#	
NOWTIME=$(date +"%Y.%m.%d--%H-%M")
echo "$NOWTIME freeling"
cd /u/metanet/tools
mkdir freeling-3.1
cd /u/metanet/tools/src
wget http://devel.cpl.upc.edu/freeling/downloads/freeling-3.1.tar.gz || echo "FAILED: rc=$? wget freeling" >&2
tar -zxvf freeling-3.1.tar.gz
cd /u/metanet/tools/src/freeling-3.1/
export TEMPLDFLAGS=${LDFLAGS}
unset LDFLAGS
env
./configure --prefix=/u/metanet/tools/freeling-3.1 || echo "FAILED: rc=$? feeling configure" >&2
make || echo "FAILED: rc=$? freeling make" >&2
make install || echo "FAILED: rc=$? freeling make install" >&2
export LDFLAGS=${TEMPLDFLAGS}
unset TEMPLDFLAGS
cd /u/metanet/tools64
ln -s ../tools/freeling-3.1 freeling-3.1
echo "$NOWTIME freeling complete"
