#!/bin/bash
#
# install tomcat 7.0.47
# metanet.bashrc sets CATALINA_HOME
cd /u/metanet/tools64
wget http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.47/bin/apache-tomcat-7.0.47.tar.gz || echo "FAILED: rc=$? wget tomcat" >&2
tar -zxvf apache-tomcat-7.0.47  || echo "FAILED: rc=$? untar tomcat" >&2
