#!/bin/bash
#
# install BLAS
cd /u/metanet/tools64
mkdir src
cd src
wget http://www.netlib.org/blas/blas.tgz || echo "FAILED: rc=$? wget blas" >&2
tar -zxvf blas.tgz
cd BLAS
gfortran -O3 -std=legacy -m64 -fno-second-underscore -fPIC -c *.f || echo "FAILED: rc=$? compile blas " >&2
ar r libfblas.a *.o
ranlib libfblas.a
rm -rf *.o
export BLAS=/u/metanet/tools64/src/BLAS/libfblas.a
