#!/bin/bash
#
# install freeling
cd /u/metanet/tools
mkdir freeling-1666
#rsync -avzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/tools/src/freeling-1666 /u/metanet/tools/src  ||  echo "FAILED: rc=$? freeling rsync" >&2
cd /u/metanet/tools/src/freeling-1666/
export TEMPLDFLAGS=${LDFLAGS}
export TEMPPATH=${PATH}
unset LDFLAGS
export PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
aclocal || echo "FAILED: rc=$? freeling aclocal" >&2
libtoolize || echo "FAILED: rc=$? freeling libtoolize" >&2
autoconf || echo "FAILED: rc=$? freeling autoconf" >&2
automake -a || echo "FAILED: rc=$? freeling automake" >&2
./configure --prefix=/u/metanet/tools/freeling-1666 || echo "FAILED: rc=$? freeling configure" >&2
make || echo "FAILED: rc=$? freeling make" >&2
make install || echo "FAILED: rc=$? freeling make install" >&2
export LDFLAGS=${TEMPLDFLAGS}
export PATH=${TEMPPATH}
unset TEMPLDFLAGS
unset TEMPPATH
