#!/bin/bash
# build metanet environment 
# Steve Doubleday
# 
export PATH=${PATH}:/home/mnauto/vmbin
#
# clone /u/metanet/etc and source metanet.bashrc after updating references to /n/picnic/xw/metanet to /u/metanet and changing JAVA reference
cd /u/metanet
git clone ssh://sjdayday@mirto1.icsi.berkeley.edu/u/metanet/git/metanet-etc.git/ etc
cd /u/metanet/etc
sed -i 's_/n/picnic/xw/metanet_/u/metanet_' metanet.bashrc
sed -i 's/oracle.x86_64/openjdk.x86_64/' metanet.bashrc
/usr/bin/printf "\nexport HOST=\$(hostname | cut -f1 -d.)\nif [ -f /u/metanet/etc/metanet.bashrc ] ; then\n source /u/metanet/etc/metanet.bashrc\nfi\n" >> /home/mnauto/.bashrc
source ~/.bashrc
#
# directories for logging and test
NOW=$(date +"%Y-%m-%d--%H-%M")
cd /home/mnauto
mkdir log-$NOW 
mkdir test-$NOW
#
# install freeling
build_freeling64
