#!/bin/bash
#
# install freeling
NOWTIME=$(date +"%Y.%m.%d--%H-%M")
echo "$NOWTIME freeling"
cd /u/metanet/tools64/src
wget http://devel.cpl.upc.edu/freeling/downloads/freeling-3.1.tar.gz || echo "FAILED: rc=$? wget freeling" >&2
tar -zxvf freeling-3.1.tar.gz
cd /u/metanet/tools64/src/freeling-3.1/
./configure --prefix=/u/metanet/tools64 || echo "FAILED: rc=$? feeling configure" >&2
make || echo "FAILED: rc=$? freeling make" >&2
make install || echo "FAILED: rc=$? freeling make install" >&2
echo "$NOWTIME freeling complete"
