#!/bin/bash
# build metanet environment 
# Steve Doubleday
# 
export PATH=${PATH}:/home/mnauto/vmbin
#
# clone /u/metanet/etc and source metanet.bashrc after updating references to /n/picnic/xw/metanet to /u/metanet and changing JAVA reference
cd /u/metanet
git clone ssh://sjdayday@mirto1.icsi.berkeley.edu/u/metanet/git/metanet-etc.git/ etc
cd /u/metanet/etc
sed -i 's_/n/picnic/xw/metanet_/u/metanet_' metanet.bashrc
sed -i 's/oracle.x86_64/openjdk.x86_64/' metanet.bashrc
/usr/bin/printf "\nexport HOST=\$(hostname | cut -f1 -d.)\nexport PATH=\$HOME/bin:\$HOME/vmbin:\$PATH\nif [ -f /u/metanet/etc/metanet.bashrc ] ; then\n source /u/metanet/etc/metanet.bashrc\nfi\nmydevpath\necho pythonpath \$PYTHONPATH\n" >> /home/mnauto/.bashrc
source ~/.bashrc
env
#
# directories for logging and test
NOW=$(date +"%Y-%m-%d--%H-%M")
cd /home/mnauto
mkdir log-$NOW 
mkdir test-$NOW
#
# install BLAS; manual export needed for scipy
build_blas
export BLAS=/u/metanet/tools64/src/BLAS/libfblas.a
#
# install lapack; manual export needed for scipy
build_lapack
export LAPACK=/u/metanet/tools64/src/lapack-3.5.0/liblapack.a
#
# install lxml2 (needed for lxml)
build_lxml2
#
# install lxslt (needed for lxml)
build_lxslt
#
# install python packages
build_python_packages
#
# install scipy (needs BLAS, lapack and numpy)
build_scipy
#
# install freeling; workaround local mods by installing 1666 instead of 3.1
#build_freeling
build_freeling1666
#
# install ant
build_ant
#
# install tomcat and sesame
build_tomcat-sesame
#
# finished building programs...
# note:  error checking depends on hard-coded error filename
#
echo "Finished building programs." >&2
ANY_ERROR=$(grep 'FAILED:' /home/mnauto/vmbin/build_err.txt | wc -l)
#
# ...copy over needed data
cd ~/vmbin
load_data 2> data_err.txt > data_out.txt
#
# if no errors, continue with tests
  if [ $ANY_ERROR -ne 0 ]
    then
      echo "Errors encountered; exiting before tests." >&2
      log_output log-$NOW
      exit 1
  fi
# ...tests
run_tests test-$NOW 2> test_err.txt > test_out.txt
#
log_output log-$NOW
exit 0
