#!/bin/bash
#
# load data
# use -rlt instead of -a to avoid permissions problems
# 
echo "set up mnauto home directories"
cd /home/mnauto
mkdir logs
git clone ssh://sjdayday@mirto1.icsi.berkeley.edu/u/metanet/git/gmr-scripts.git/ bin || echo "FAILED: rc=$? git mnauto bin" >&2
git clone ssh://sjdayday@mirto1.icsi.berkeley.edu/u/metanet/git/metanetdev.git/ mdev || echo "FAILED: rc=$? git mnauto mdev" >&2
cd mdev
ant install || echo "FAILED: rc=$? ant install"
cd /u/metanet
mkdir dev
# dev is a link, so copy its contents
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/dev/  /u/metanet/dev || echo "FAILED: rc=$? rsync dev" >&2
echo "tools, excluding ones we already built or know we don't need"
rsync -rltqzhe ssh --exclude-from '/home/mnauto/vmbin/exclude-tools64.txt' sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/tools64/ /u/metanet/tools64 || echo "FAILED: rc=$? rsync tools" >&2
echo "affectRatings"
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/affectRatings /u/metanet || echo "FAILED: rc=$? rsync affectRatings" >&2
echo "clustering"
cd /u/metanet
mkdir clustering
cd clustering
mkdir m4source
cd m4source
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/clustering/m4source/master_dim_list_new.csv /u/metanet/clustering/m4source/ || echo "FAILED: rc=$? rsync list_new" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/clustering/m4source/lexicon_english.txt /u/metanet/clustering/m4source/ || echo "FAILED: rc=$? rsync EN lexicon" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/clustering/m4source/termtermmatrix_english.mat /u/metanet/clustering/m4source/ || echo "FAILED: rc=$? rsync EN matrix" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/clustering/m4source/dictionary_spanish.dict /u/metanet/clustering/m4source/ || echo "FAILED: rc=$? rsync ES dict" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/clustering/m4source/modelspanish.lsi /u/metanet/clustering/m4source/ || echo "FAILED: rc=$? rsync ES model" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/clustering/m4source/dictionary_russian.dict /u/metanet/clustering/m4source/ || echo "FAILED: rc=$? rsync RU dict" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/clustering/m4source/modelrussian.lsi /u/metanet/clustering/m4source/ || echo "FAILED: rc=$? rsync RU model" >&2
cd /u/metanet
mkdir corpolexica
cd corpolexica
mkdir EN
mkdir ES
mkdir RU
mkdir FA
echo "EN bnc"
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/corpolexica/EN/bnc /u/metanet/corpolexica/EN || echo "FAILED: rc=$? rsync EN bnc" >&2
cd /u/metanet/corpolexica/ES
mkdir freeling
echo "ES relationsDB"
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/corpolexica/ES/freeling/relations.db /u/metanet/corpolexica/ES/freeling || echo "FAILED: rc=$? rsync ES relationsDB" >&2
cd /u/metanet/corpolexica/RU
mkdir malt
echo "RU relationsDB"
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/corpolexica/RU/malt/relations.db /u/metanet/corpolexica/RU/malt || echo "FAILED: rc=$? rsync RU relationsDB" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/AssignMappings /u/metanet || echo "FAILED: rc=$? rsync assign mappings" >&2
echo "corpolexica m4mappings"
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/corpolexica/EN/m4mapping /u/metanet/corpolexica/EN || echo "FAILED: rc=$? rsync EN m4mapping" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/corpolexica/ES/m4mapping /u/metanet/corpolexica/ES || echo "FAILED: rc=$? rsync ES m4mapping" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/corpolexica/RU/m4mapping /u/metanet/corpolexica/RU || echo "FAILED: rc=$? rsync RU m4mapping" >&2
cd /u/metanet
mkdir nlptools
cd nlptools
echo "nlptools"
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/nlptools/maltparser-1.8 /u/metanet/nlptools || echo "FAILED: rc=$? rsync maltparser1.7" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/nlptools/tree-tagger-3.2 /u/metanet/nlptools || echo "FAILED: rc=$? rsync tree-tagger" >&2
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/nlptools/stanford-postagger-full-2014-06-16 /u/metanet/nlptools || echo "FAILED: rc=$? rsync pos-tagger" >&2
cd /u/metanet/corpolexica/RU
mkdir parsers
cd parsers
mkdir tools
echo "RU parser"
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/corpolexica/RU/parsers/tools/parser /u/metanet/corpolexica/RU/parsers/tools || echo "FAILED: rc=$? rsync RU parser" >&2
cd /u/metanet/
mkdir persianCode
cd persianCode
mkdir PersianPipeline
cd PersianPipeline
echo "Persian models"
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/persianCode/PersianPipeline/models /u/metanet/persianCode/PersianPipeline  || echo "FAILED: rc=$? rsync Persian models" >&2
cd /u/metanet
mkdir extraction 
echo "extraction seeds cxns persian"
cd extraction
git clone ssh://sjdayday@mirto1.icsi.berkeley.edu/u/metanet/git/seeds.git/ seeds|| echo "FAILED: rc=$? git seeds" >&2
git clone ssh://sjdayday@mirto1.icsi.berkeley.edu/u/metanet/git/cxns.git/ cxns  || echo "FAILED: rc=$? git cxns" >&2
mkdir persian
rsync -rltqzhe --exclude=oldLogs --exclude=logs ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/extraction/persian/lms2 /u/metanet/extraction/persian || echo "FAILED: rc=$? rsync persian lms2" >&2
cd /u/metanet
mkdir IARPATesting
echo "IARPATesting"
rsync -rltqzhe --exclude='iarpa*' --exclude='bak*' ssh sjdayday@mirto1.icsi.berkeley.edu:/u/metanet/IARPATesting/gold /u/metanet/IARPATesting || echo "FAILED: rc=$? rsync gold" >&2
cd /u/framenet
mkdir lib
echo "framenet"
rsync -rltqzhe ssh sjdayday@mirto1.icsi.berkeley.edu:/u/framenet/lib/nltk_data /u/framenet/lib || echo "FAILED: rc=$? rsync nltk_data" >&2
echo "data loaded"
exit 0
